### ISSUE TITLE
[Enhancement] Matter Overdrive integration

### ISSUE THREAD

**Issue by Buttcrackofthunder** [MinecraftModDevelopmentMods/Armory-Expansion#3]
Matter Overdrive:
https://minecraft.curseforge.com/projects/matteroverdrive

There are two materials in this mod, Tritanium and Dilithium. Tritanium has about 6x the durability of iron and keeps its mining level, but its speed is about that of stone.

Dilithium is a crystal, more like quartz, and could perhaps be used as a modifier.

Matter Overdrive also has a "matter" system, whth every supported item having its own value, the ability to break down materials into "matter plasma" and use that plasma to create other items, EE style. 

perhaps adding a dilithium crystal to a tinker's tool/armor alongside a tank could allow the item to store some matter plasma, which it uses to repair itself slowly.

**Comment by YaibaToKen** [comment]
Side note on the matter tank, how easy is it to produce large amounts of matter during mid to late game?
Afaik, RF modifiers were removed from TiC due to how OP they were, essentially making the tool unbreakable for barely any cost.

**Comment by YaibaToKen** [comment]
Fluid IMC integration isn't fully working but I expect that to be the only real impediment for a proper release of this integration.

**Comment by YaibaToKen** [comment]
Dropped Matter Overdrive support
